#!/usr/bin/env bash
#
# apply-load-gen.sh — generate synthetic full-history packfiles for the
# bench-fullhistory suite using stellar-core's `apply-load`.
#
# Pipeline:
#   1. stellar-core new-db + new-hist + apply-load  -> meta.xdr (framed
#      LedgerCloseMeta stream of dense synthetic ledgers)
#   2. bench-fullhistory cold-ingest --source=lcm   -> cold packfiles
#      (ledgers/, txhash/, events/) in the layout the read benches expect
#   3. build-txhash-index                            -> cold tx-hash MPHF
#
# The cold-* read benches then point --cold-dir at <out>/cold/ledgers (etc).
#
# WORKLOAD PROFILES (model transaction + density):
#   sac       Stellar Asset Contract transfers   (target ~10k SAC TPS)
#   token     custom (OpenZeppelin-style) token  (target  ~9k OZ  TPS)
#   soroswap  Soroswap AMM swaps                  (target ~2.5k    TPS)
#
# TPS is interpreted as txs-per-ledger / ledger-close-time. With the default
# CLOSE_TIME_S=1 the per-ledger transaction counts below hit the targets; for
# SAC the count is divided by APPLY_LOAD_BATCH_SAC_COUNT (each tx batches that
# many SAC invocations, and TPS counts each invocation).
#
# REQUIREMENTS
#   * stellar-core built with BUILD_TESTS (apply-load + ARTIFICIALLY_GENERATE_
#     LOAD_FOR_TESTING). The public CI build is tagged e.g.
#     `26.x.y-NNNN.<sha>.noble~buildtests`.
#   * The bench-fullhistory binary (this script builds it if --bench-bin unset).
#
# COST WARNING (real full chunks): each chunk is 10,000 ledgers, and a chunk
# at 9k txs/ledger applies 90M transactions. 16 chunks of dense Soroban load is
# many hours to days of apply time and tens of GB of meta. Start with
# CHUNKS=1 to validate the pipeline before scaling up.
#
set -euo pipefail

# ---- knobs (env-overridable) -----------------------------------------------
PROFILE="${PROFILE:-sac}"                 # sac | token | soroswap
CHUNKS="${CHUNKS:-16}"                     # number of 10k-ledger chunks to fill
CLOSE_TIME_S="${CLOSE_TIME_S:-1}"          # assumed ledger close time for TPS math
TXS_PER_LEDGER="${TXS_PER_LEDGER:-}"       # override the profile's per-ledger tx count
CORE_BIN="${CORE_BIN:-$(command -v stellar-core || true)}"
BENCH_BIN="${BENCH_BIN:-}"                 # prebuilt bench-fullhistory; built if empty
OUT_ROOT="${OUT_ROOT:-./apply-load-out}"   # work + output root
TYPES="${TYPES:-ledgers,txhash,events}"    # cold-ingest types
CHUNK_WORKERS="${CHUNK_WORKERS:-4}"        # cold-ingest chunk concurrency
KEEP_META="${KEEP_META:-0}"                # 1 = keep meta.xdr after ingest
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LEDGERS_PER_CHUNK=10000

log() { printf '\033[1;34m[apply-load-gen]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[apply-load-gen] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ---- resolve core + verify BUILD_TESTS -------------------------------------
[ -n "$CORE_BIN" ] || die "stellar-core not found; set CORE_BIN=/path/to/stellar-core (must be a BUILD_TESTS build)"
[ -x "$CORE_BIN" ] || die "CORE_BIN=$CORE_BIN is not executable"
CORE_VER="$("$CORE_BIN" version 2>/dev/null | head -1 || true)"
log "stellar-core: $CORE_BIN ($CORE_VER)"
if ! "$CORE_BIN" apply-load --help >/dev/null 2>&1; then
  die "this stellar-core lacks the apply-load command — you need a BUILD_TESTS build (…~buildtests)"
fi

# ---- per-profile density ---------------------------------------------------
# model_tx, dependent_tx_clusters, batch_sac_count, target_tps
case "$PROFILE" in
  sac)      MODEL_TX="sac";          CLUSTERS=1; BATCH_SAC=100; TARGET_TPS=10000 ;;
  token|oz) MODEL_TX="custom_token"; CLUSTERS=2; BATCH_SAC=1;   TARGET_TPS=9000  ;;
  soroswap) MODEL_TX="soroswap";     CLUSTERS=1; BATCH_SAC=1;   TARGET_TPS=2500  ;;
  *) die "unknown PROFILE=$PROFILE (expected sac|token|soroswap)" ;;
esac

# txs-per-ledger so that (txs * batch) / close_time == target_tps
if [ -z "$TXS_PER_LEDGER" ]; then
  TXS_PER_LEDGER=$(( (TARGET_TPS * CLOSE_TIME_S + BATCH_SAC - 1) / BATCH_SAC ))
fi
NUM_LEDGERS=$(( CHUNKS * LEDGERS_PER_CHUNK ))
GENESIS_ACCOUNTS=$(( TXS_PER_LEDGER * 2 ))
[ "$GENESIS_ACCOUNTS" -lt 21000 ] && GENESIS_ACCOUNTS=21000

log "profile=$PROFILE model_tx=$MODEL_TX txs/ledger=$TXS_PER_LEDGER batch_sac=$BATCH_SAC -> ~$(( TXS_PER_LEDGER * BATCH_SAC / CLOSE_TIME_S )) TPS @ ${CLOSE_TIME_S}s close"
log "chunks=$CHUNKS num_ledgers=$NUM_LEDGERS (this is the slow part — apply-load closes every ledger)"

# ---- workspace + config ----------------------------------------------------
WORK_DIR="$OUT_ROOT/$PROFILE/work"
COLD_OUT="$OUT_ROOT/$PROFILE/cold"
mkdir -p "$WORK_DIR" "$COLD_OUT"
CONF="$WORK_DIR/apply-load.cfg"
META="$WORK_DIR/meta.xdr"

cat > "$CONF" <<EOF
# Auto-generated by apply-load-gen.sh — profile=$PROFILE
# Benchmark mode with the $MODEL_TX model transaction, meta output ENABLED so
# the closed ledgers can be turned into bench packfiles. (The upstream
# apply-load-benchmark-*.cfg disable meta because they only time apply.)
APPLY_LOAD_MODE="benchmark"
APPLY_LOAD_MODEL_TX="$MODEL_TX"

# --- meta output (required by this driver) ---
METADATA_OUTPUT_STREAM="meta.xdr"
DISABLE_TX_META_FOR_TESTING=false
METADATA_DEBUG_LEDGERS=0

# --- density / size ---
APPLY_LOAD_MAX_SOROBAN_TX_COUNT=$TXS_PER_LEDGER
APPLY_LOAD_LEDGER_MAX_DEPENDENT_TX_CLUSTERS=$CLUSTERS
APPLY_LOAD_BATCH_SAC_COUNT=$BATCH_SAC
APPLY_LOAD_NUM_LEDGERS=$NUM_LEDGERS
GENESIS_TEST_ACCOUNT_COUNT=$GENESIS_ACCOUNTS

# Bucket-list pre-generation disabled (benchmark mode operates on model state).
APPLY_LOAD_BL_SIMULATED_LEDGERS=0
APPLY_LOAD_BL_WRITE_FREQUENCY=0
APPLY_LOAD_BL_BATCH_SIZE=0
APPLY_LOAD_BL_LAST_BATCH_SIZE=0
APPLY_LOAD_BL_LAST_BATCH_LEDGERS=0

# --- apply-load boilerplate ---
ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
ENABLE_SOROBAN_DIAGNOSTIC_EVENTS=false
DISABLE_SOROBAN_METRICS_FOR_TESTING=true
APPLY_LOAD_TIME_WRITES=true

# --- node boilerplate ---
RUN_STANDALONE=true
NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"
NODE_SEED="SDQVDISRYN2JXBS7ICL7QJAEKB3HWBJFP2QECXG7GZICAHBK4UNJCWK2 self"
LOG_FILE_PATH=""

[QUORUM_SET]
THRESHOLD_PERCENT=100
VALIDATORS=["\$self"]

# Local history archive — lets core publish the pre-benchmark checkpoint.
[HISTORY.local]
get="cp -r history/{0} {1}"
put="cp -r {0} history/{1}"
mkdir="mkdir -p history/{0}"
EOF
log "wrote config: $CONF"

# ---- run apply-load --------------------------------------------------------
log "stellar-core new-db…"
( cd "$WORK_DIR" && "$CORE_BIN" new-db --conf "$CONF" ) >/dev/null
log "stellar-core new-hist local…"
( cd "$WORK_DIR" && "$CORE_BIN" new-hist local --conf "$CONF" ) >/dev/null
log "stellar-core apply-load… (this is the long-running step)"
APPLY_LOG="$WORK_DIR/apply-load.log"
( cd "$WORK_DIR" && "$CORE_BIN" apply-load --conf "$CONF" ) 2>&1 | tee "$APPLY_LOG"

[ -s "$META" ] || die "apply-load produced no meta at $META.
  Your core may not emit metadata in benchmark mode. Workaround: base the config
  on docs/apply-load-for-meta.cfg (APPLY_LOAD_MODE=ledger-limits), which is the
  proven meta-emitting path, and re-run with --source=lcm."

# Pre-benchmark checkpoint: ledgers with seq <= this are setup, not benchmark.
CHECKPOINT="$(grep -oE 'Published final checkpoint before benchmark: ledger [0-9]+' "$APPLY_LOG" \
  | grep -oE '[0-9]+$' | tail -1 || true)"
CHECKPOINT="${CHECKPOINT:-0}"
log "pre-benchmark checkpoint = $CHECKPOINT (skipping ledgers with seq <= $CHECKPOINT)"
log "meta.xdr size: $(du -h "$META" | cut -f1)"

# ---- build bench binary if needed ------------------------------------------
if [ -z "$BENCH_BIN" ]; then
  BENCH_BIN="$WORK_DIR/bench-fullhistory"
  log "building bench-fullhistory -> $BENCH_BIN"
  ( cd "$SCRIPT_DIR" && go build -o "$BENCH_BIN" . )
fi

# ---- cold-ingest via the lcm source ----------------------------------------
# --chunk=1 (chunk 0 is reserved/“unset”); baseChunk=1 maps chunk 1 -> block 0.
log "cold-ingest --source=lcm (types=$TYPES, chunks=$CHUNKS)…"
"$BENCH_BIN" cold-ingest \
  --source=lcm \
  --lcm-file="$META" \
  --lcm-checkpoint="$CHECKPOINT" \
  --types="$TYPES" \
  --chunk=1 \
  --num-chunks="$CHUNKS" \
  --chunk-workers="$CHUNK_WORKERS" \
  --cold-out-dir="$COLD_OUT" \
  --xdr-views \
  --out="$WORK_DIR/bench-out"

# ---- build the cold tx-hash index ------------------------------------------
if [[ ",$TYPES," == *",txhash,"* ]]; then
  log "build-txhash-index…"
  "$BENCH_BIN" build-txhash-index \
    --in-dir="$COLD_OUT/txhash" \
    --idx-out="$COLD_OUT/txhash.idx" \
    --out="$WORK_DIR/bench-out"
fi

[ "$KEEP_META" = "1" ] || { log "removing meta.xdr (set KEEP_META=1 to keep)"; rm -f "$META"; }

log "DONE. Cold packfiles: $COLD_OUT/{ledgers,txhash,events}"
cat >&2 <<EOF

Next — point the read benches at the synthetic cold store, e.g.:

  $BENCH_BIN cold-ledgers  --cold-dir=$COLD_OUT/ledgers --n=20 --iters=60 \\
      --query-concurrency=1,4,8,16 --out=results-$PROFILE
  $BENCH_BIN cold-txpage   --cold-dir=$COLD_OUT/ledgers --chunk-lo=1 --chunk-hi=$CHUNKS \\
      --page-size=20 --iters=200 --query-concurrency=1,4,8,16 --out=results-$PROFILE
  $BENCH_BIN cold-txhash   --cold-dir=$COLD_OUT/ledgers \\
      --txhash-cold-mphf=$COLD_OUT/txhash.idx --iters=1000 --out=results-$PROFILE
  $BENCH_BIN cold-events   --cold-events-dir=$COLD_OUT/events/00000 --iters=500 --out=results-$PROFILE
EOF
