name: Go
on:
  push:
    branches: [ main, release/** ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow the action to annotate code in the PR.
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml

      - uses: ./.github/actions/setup-go

      - uses: stellar/actions/rust-cache@main
      - name: Build libpreflight
        run: |
          rustup update
          make build-libs

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2 # this is the golangci-lint version
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: true
